server:
  port: 8081
javafamily:
  notify:
    feishu:
      hook-url: https://open.feishu.cn/open-apis/bot/v2/hook/af4a5e09-15ac-411e-830e-fb2904609fad
      enabled: true  # ??????, ??????????(??, ??, ??), ??? true
